In [ ]:
import numpy as np

## Working with Arrays using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
      

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## Using Reshape funciton to convert single dimension array to two dimnenson
## you cannot give lenght of second dimension, in this case 5 below 5
## Because array alreay has 5 elements in it

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

[1 2 3 4 5]


In [ ]:
## Using standard method to create two dimensional array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2 )
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
## Numpy Vectorized operations
arr1=np.array([1,2,3,4,5])
arr2 =np.array([2,4,8,2,1])

##Element Wise Addition
print("Addition ", arr1+arr2 )

##Element Wise Subtraction
print("Subtraction ", arr1-arr2 )

##Element Wise Mutiplication
print("Mutiplication ", arr1*arr2 )

##Element Wise Division
print("Division ", arr1/arr2)


Addition  [ 3  6 11  6  6]
Subtraction  [-1 -2 -5  2  4]
Mutiplication  [ 2  8 24  8  5]
Division  [0.5   0.5   0.375 2.    5.   ]


In [12]:
## Numpy Universal Functions
arr1=np.array([1,2,3,4,5])

##Element Wise Square Root
print("Square Root ", np.sqrt(arr1))

##Element Wise Exponential
print("Exponential ", np.exp(arr1))

##Element Wise Sin
print("Sin ", np.sin(arr1))

##Element Wise Log
print("log ", np.log(arr1))


Square Root  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sin  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## Array Slicing and Indexing
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6],[9,2,8,2,3]])
#print('Array: \n', arr3)

#arr3[1:,3:]
arr3[0:3,0:2] ## 0:3  first entry on left side indicates which rows to be picked up 0:2 is for columns




array([[1, 2],
       [2, 3],
       [9, 2]])

In [ ]:
## Normalization
